### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by NeoLegends**
Hey!

I thought I'd add some typings for the library. :) Would love to see this merged, but if not that's okay as well (I'd publish to @types instead). I hope I typed everything correctly.

### CODE REVIEW

**Comment by bcomnes** [comment]
I'm fine with it.  Thanks!

**Comment by NeoLegends** [comment]
So you plan on merging this? :)

**Comment by bcomnes** [comment]
@NeoLegends had a busy week last week, apologies.  We aren't currently using TS at Netlify.  Would you be interest to periodically review/contribute updates to these as we make changes/additions to the library?

**Comment by NeoLegends** [comment]
Sure. Just notify me in this thread (or via email or something) if you have breaking changes and I don't notice them myself. :)

**Comment by bcomnes** [comment]
Sounds good!  I'll land this today.

**Pull request merged**
