### PR TITLE
recoverSession to try to getUserData before cookie

### LINKED ISSUE #39: recoverSession should not just check cookie, it should try to getUserData as well
so that if anything changes on the netlify identity side it woulnt have outdated info e.g. https://github.com/netlify/gotrue-js/blob/86ee9894e4514d3fdc83208f3152d8311a6da297/src/user.js#L24

### PR DESCRIPTION
**Pull request by abhijithvijayan**
Fixes #39

### CODE REVIEW

**Comment by abtx** [comment]
Any follow up on this PR?

**Comment by abhijithvijayan** [comment]
:grin:

**Comment by jjenzz** [comment]
@abhijithvijayan This PR doesn't appear to introduce any changes other than moving an existing method? Is there some additional code that needs to be pushed?

I'm running into an issue with this atm I believe and was hoping for a fix 😬

**Comment by abhijithvijayan** [comment]
@jjenzz The fix is to call getUserData() before the cookie.

This was a suggested fix somewhere discussed(not exactly remember as I opened this an year ago)

**Comment by jjenzz** [comment]
> @jjenzz The fix is to call getUserData() before the cookie.
> 
> This was a suggested fix somewhere discussed(not exactly remember as I opened this an year ago)

The changes in this PR don’t include a method call. Am I going bonkers? Haha. I’m wondering if part of your original change was merged in another PR...

**Comment by abhijithvijayan** [comment]
I am not sure about this anymore.

Closing.

**Comment by abtx** [comment]
@abhijithvijayan can you explain a bit more about the fix?

**Comment by abhijithvijayan** [comment]
@abtx to be honest. I dont remember.

I remember reading some github discussion about this issue, asking to put the definition on top(like in the PR).

I dont know if that changes anything.

If it synchronously executes, probably this is a valid PR. Else, :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
