### PR TITLE
Add nodejs (and possibly old browsers) support

### PR DESCRIPTION
**Pull request by Cethy**
Adds `es6-promise`, `isomorphic-base64` & `isomorphic-fetch` as deps.

Note : Browser version grow from `19ko` to `45ko` or (`30ko` w/o es6-promise polyfill).

### CODE REVIEW

**Comment by cameronmcefee** [comment]
I'm looking for this support myself right now, so I can use it via Netlify functions

**Comment by Cethy** [comment]
@cameronmcefee Glad to see I'm not the only one with the use-case ;)

**Comment by cameronmcefee** [comment]
I just noticed in the docs that [Netlify functions have access to identity](https://www.netlify.com/docs/functions/#identity-and-functions). I need to investigate, but this may cover my case.

**Comment by cameronmcefee** [comment]
The answer is more involved than what you're trying to accomplish here, but if you're curious, The api is documented here: https://github.com/netlify/gotrue. The Netlify functions come with a token which can be used to make requests

**Comment by Cethy** [comment]
Yeah, I'm aware of this part of the docs (can be useful for anyone stumbling on this issue, nonetheless). 

But it does not cover my use-case : for the `context.clientContext` to work, you need a user authenticated on your website beforehand. 
My use-case was to allow any visitor to trigger some mechanism, which would use `git-gateway`, service needing an authenticated user (for obvious security reason). 
So I ended up creating a user in Identity with its credentials living in my lambda function.

In the end, I simplified the workflow and avoid using `Identity` and `git-gateway`.
Still, i think it could help.

AFAIK, the browser & node support is not documented anywhere and could bite a lot of people :
Didn't test it myself, but [caniuse  says it does not work on ie11 or opera mini](https://caniuse.com/#search=fetch) (approx 5% of users)

**Comment by NeoLegends** [comment]
I must say I'm strictly against this. IMO people should polyfill themselves (like include a script tag that does all the necessary polyfilling before you include your code) instead of putting the additional size burden on everybody using this library. We, for example, only target browsers that have promise support, while at the same time, we very much care about making our site load as quickly as possible. This means every kb of JS that can be removed counts. Increasing the size of this library from 19kb to 45kb (thats more than double the original size!) doesn't help very much with this.

**Comment by bcomnes** [comment]
A possible solution is documenting the polyfills as well.

**Comment by erezrokah** [comment]
Closing as stale, this should be done (when given a relevant use case) via `babel-present-env` and `browserslist` and not manually.
We can do this once we bring our build tooling up to speed

**Pull request closed without merging**
